### ISSUE TITLE
Course Accordions (+ / -) should be expanded based on "active course"  

### ISSUE THREAD

**Issue by sgerritse** [MastermindMedia/EliteFX#1]
Go to this page: http://hrsearchgroup.com/courses/ 

- If user has not started any courses, the first "Course Accordion" should be expanded by default. 
![screen shot 2017-01-31 at 3 26 07 pm](https://cloud.githubusercontent.com/assets/10511034/22483098/c5915f50-e7c9-11e6-9a08-9517d9c3fc8c.png)

-  Whatever "Course" the user is active in, it should be expanded.
![screen shot 2017-01-31 at 3 26 19 pm](https://cloud.githubusercontent.com/assets/10511034/22483144/f003444c-e7c9-11e6-8fe1-6470ec03c1bc.png)

**Comment by sgerritse** [comment]
This is not completed / or function correctly - When I log into (Mastervi / Admin4web) you can see the courses but none of them are expanded. 

- The current "Active Course" accordion should always be expanded. 
- Any "Finished Course" should should be closed (But they can still open the accordion manually)

**Comment by sumeena** [comment]
done.
