### ISSUE TITLE
Fixing stats on "Marketing Stats" page

### ISSUE THREAD

**Issue by sgerritse** [MastermindMedia/EliteFX#12]
http://hrsearchgroup.com/marketing-stats/ 

This page has a few missing elements, it is not finished. 
- If no data to "track", user is just a "guest"...than it should look like this:
- Eye Icon is "Greyed out" because it is not clickable.

![guest-view](https://cloud.githubusercontent.com/assets/10511034/22490979/681e71a8-e7ee-11e6-9ae5-96c0d72ec4b0.jpg)

**Comment by sumeena** [comment]
issue done, 
Updated on live
