### ISSUE TITLE
Display "Active User" data on "User View" popup 

### ISSUE THREAD

**Issue by sgerritse** [MastermindMedia/EliteFX#13]
Go to http://hrsearchgroup.com/marketing-stats/ and click on "Active User" view icon.

![screen shot 2017-01-31 at 7 52 24 pm](https://cloud.githubusercontent.com/assets/10511034/22491049/d0f77508-e7ee-11e6-82a4-b9ae512865d2.png)

Popup appears with "Active User" information. 

![screen shot 2017-01-31 at 7 51 11 pm](https://cloud.githubusercontent.com/assets/10511034/22491023/a6f36ef6-e7ee-11e6-9e58-9f15f28beb0a.png)

- Remove, Share button from "user popup".
- Make sure "Profile Picture" will show if uploaded.
- Make sure correct "Membership" dates / colors are showing.
![screen shot 2017-01-31 at 7 55 23 pm](https://cloud.githubusercontent.com/assets/10511034/22491123/3b5e1bf4-e7ef-11e6-95be-b4c542d62ae9.png)

**Comment by nitubasra** [comment]
All below mentioned issues are fixed.

Remove, Share button from "user popup".
Make sure "Profile Picture" will show if uploaded.
Make sure correct "Membership" dates / colors are showing.

Please review.
