### ISSUE TITLE
Style Rocket.Chat Popout

### ISSUE THREAD

**Issue by sgerritse** [MastermindMedia/EliteFX#14]
Rocket.Chat should function like this:
![full-chat](https://cloud.githubusercontent.com/assets/10511034/22491245/3262f226-e7f0-11e6-8590-53e0178040c7.gif)

Make sure chat has the following on each page:
 - The "Go back to System" icon on left.
![screen shot 2017-01-31 at 7 58 51 pm](https://cloud.githubusercontent.com/assets/10511034/22491283/6cab00b8-e7f0-11e6-939b-4d561522aee1.png)

- "Open in new window" on the right. 
![screen shot 2017-01-31 at 8 05 00 pm](https://cloud.githubusercontent.com/assets/10511034/22491320/92cb667a-e7f0-11e6-8e8e-797ec744e529.png)

- The "ETA Chat" button, should open in new tab when clicked on mobile device. 
(Instead of having the slide effect)

**Comment by jben0324** [comment]
Updated the Style and modified function for mobile. The only remaining is the icon for desktop(For open new window)

**Comment by sgerritse** [comment]
Make sure this function is throughout the entire website - wherever the chat is.

All pages except for the dashboard have this function.
http://hrsearchgroup.com/courses/ (See here)

**Comment by jben0324** [comment]
I forgot that you moved the code before in the dashboard page. i already fixed it
