### ISSUE TITLE
Checkout Process Not Working "Fully"

### ISSUE THREAD

**Issue by sgerritse** [MastermindMedia/EliteFX#18]
The Content Restriction / Membership plugin was changed, and now the registration process doesn't seem to work "Fully".

Note: It creates the "User", but it just keeps loading and loading instead of taking the user to the "Single Checkout Page, http://hrsearchgroup.com/single-checkout-page/".

* Update: It does take user to checkout, but takes almost 5 minutes.
* When user does get forwarded, it gives "Internal Server Error" on checkout.

1. http://hrsearchgroup.com/survey/
2. http://hrsearchgroup.com/how-trading-should-be/
3. http://hrsearchgroup.com/how-it-works/
4. http://hrsearchgroup.com/serious-proof/
5. http://hrsearchgroup.com/main-sales-page/

**Comment by sumeena** [comment]
Hi

I have fixed the issue on live site.
As this issue was due to confliction between the two plugins which are not used by the website.
So I deactivated those plugins.


Thanks
