### ISSUE TITLE
Getting "Object" Error on "Notifications"

### ISSUE THREAD

**Issue by sgerritse** [MastermindMedia/EliteFX#19]
The notification icon has a dropdown, anytime it is clicked - I receive a "Object Error".
![screen shot 2017-02-08 at 12 14 52 am](https://cloud.githubusercontent.com/assets/10511034/22724427/ee4ddd54-ed93-11e6-9021-40ab310efbce.png)

- Make "Blue Text" links, which go to page of notification.
-- EX: If it is a "Signal Notification" it would go to signal page.
-- EX: If it is a "Blog Notification" it would go to blog page.

- Remove the "See All" tab on dropdown.

**Comment by sumeena** [comment]
I have done the issue
Now it will show the dynamic data, it was showing static earlier.
and when user will click on notification icon and opens that notification, it will redirect the user to specific page.

**Comment by sgerritse** [comment]
I noticed that when I log into another user (Mastervi / Admin4web) and click on the notifications dropdown. Says "MasterVi" has released new...

![screen shot 2017-02-09 at 1 15 22 pm](https://cloud.githubusercontent.com/assets/10511034/22796856/119f80e6-eeca-11e6-8d4b-3aaf8ab5a844.png)


-  Lets Just remove the "Name" so it should always say "A New Signal / Blog Has Been Added"
- Also make sure this function is working on every single page, it only seems to be working the "Dashboard" page.

**Comment by sumeena** [comment]
Above are done

**Comment by sgerritse** [comment]
I noticed that these errors:
![screen shot 2017-02-16 at 2 07 45 pm](https://cloud.githubusercontent.com/assets/10511034/23036717/de27779a-f451-11e6-9b52-724adc74d74a.png)
