### ISSUE TITLE
"Top Menu" should be same on every page.

### ISSUE THREAD

**Issue by sgerritse** [MastermindMedia/EliteFX#22]
![screen shot 2017-02-09 at 1 25 28 pm](https://cloud.githubusercontent.com/assets/10511034/22797144/47fcdc32-eecb-11e6-8ff1-f2c7dfbfbdde.png)

- Please make sure the "Top Menu" is working on every page. (It seems to only be working on the homepage currently.)

**Comment by sumeena** [comment]
Done.
