### ISSUE TITLE
"View Demo" Popup Function

### ISSUE THREAD

**Issue by sgerritse** [MastermindMedia/EliteFX#5]
Certain pages have page "Demos Popups" on first time visit to page:

![screen shot 2017-01-31 at 3 49 58 pm](https://cloud.githubusercontent.com/assets/10511034/22483853/fe82edee-e7cc-11e6-937c-5f6c272af320.png)

- http://hrsearchgroup.com/ (Dashboard / When user is signed in)
- http://hrsearchgroup.com/courses/
- http://hrsearchgroup.com/marketing-links/
- http://hrsearchgroup.com/affiliate-statistics/
- http://hrsearchgroup.com/eta-signals/

The "Demo Popup", should only appear a max of 3 times. After the popup has been closed 3 times...the only way to bring the "Demo Popup" back is by clicking "View Demo" link on the current page.
![screen shot 2017-01-31 at 3 50 54 pm](https://cloud.githubusercontent.com/assets/10511034/22483944/5589231a-e7cd-11e6-8591-a2065f138311.png)

*Note: Each "Demo Popup" has a different "bullet points"
![screen shot 2017-01-31 at 3 54 28 pm](https://cloud.githubusercontent.com/assets/10511034/22484009/93397ffc-e7cd-11e6-971c-26ddb8ecfa21.png)

 and Each "Demo Popup" has a different video.
![screen shot 2017-01-31 at 3 55 00 pm](https://cloud.githubusercontent.com/assets/10511034/22484019/a3806a74-e7cd-11e6-8bab-e84576ccdc3b.png)

**Comment by sumeena** [comment]
hi

This is done, as if we go to the Dashboard, we cancel the pop-up three times.
and refresh the page again, it will not show the pop-up on dasboard again

 if we go to Marketing Stats page and again cancel the pop-up three times, after 4th refresh it will not show the pop-up.

So it means, every pop-up will show three times.
---- above is working fine
Or you want to show any pop-up for three times in whole site not according to each page?

**Comment by sgerritse** [comment]
The popups on these pages, appear only 3 times. 
http://hrsearchgroup.com/ (Dashboard / When user is signed in)
http://hrsearchgroup.com/courses/
http://hrsearchgroup.com/marketing-links/
http://hrsearchgroup.com/affiliate-statistics/
http://hrsearchgroup.com/eta-signals/

**Comment by sumeena** [comment]
Hey Steven
okay so i logged  in with those credentials. The pop up appears 3 times max for each page and after that it does not show up if i refresh the page or i go to another page, i have to click on the Demo button to see it. Is this not how you want it to work. Also if i logout and then sign back in, the pop-up will not show until you close the browser and opens the site again.

Do you want to open the pop-ups after logged out and sign in back again without closing the browser?

I made the video also.
Please check 
https://www.dropbox.com/s/5elcxozxlzmijrk/first.mph?dl=0
Can you check on one different system? and which OS you are checking on.? I checked on Windows, Linux, Ubuntu.

Thanks

**Comment by sgerritse** [comment]
Do you want to open the pop-ups after logged out and sign in back again without closing the browser? ---- No, once it is gone. The only way to bring back is by clicking "view demo" button.

**Comment by sumeena** [comment]
@sgerritse can you please check , now when you click the button, its counted .
